# Basic reactor configuration
metadata:
  name: "Basic Reactor Configuration"
  description: "Simple ideal gas reactor setup"
  version: "1.0"

simulation:
  mechanism: "gri30.yaml"
  time_step: 0.001
  max_time: 10.0

components:
  - id: reactor1
    type: IdealGasReactor
    temperature: 1000  # K
    pressure: 101325   # Pa
    composition: "CH4:1,O2:2,N2:7.52"
    
  - id: res1
    type: Reservoir
    temperature: 300   # K
    composition: "O2:1,N2:3.76"

connections:
  - id: mfc1
    type: MassFlowController
    source: res1
    target: reactor1
    mass_flow_rate: 0.1  # kg/s
