"""Mixing two streams example — Boulder conversion.

Boulder context
---------------

This example demonstrates how to use Boulder's sim2stone functionality to
convert a Cantera reactor network simulation to a STONE serialised ``.yaml``
format, and how to reload and re-solve it with
:class:`~boulder.runner.BoulderRunner`.

The Cantera simulation setup is imported from ``mix1.py``, which implements
the mixing example from
https://cantera.org/3.1/examples/python/reactors/mix1.html.

.. note::

    **This is the script shape generated by the Boulder GUI.**

    When you load a YAML in the Boulder interface and click
    *Download Python*, the downloaded ``.py`` file follows the same
    :meth:`~boulder.runner.BoulderRunner.solve_stage` pattern used here.
    For a multi-stage (PSR → PFR) example see
    :doc:`plot_staged_solve_from_yaml`.

Requires: cantera, boulder

.. tags:: Python, reactor network, STONE YAML, mixing, sim2stone
"""

import sys
from pathlib import Path

from boulder.runner import BoulderRunner
from boulder.sim2stone import write_sim_as_yaml

# sphinx-gallery sets cwd to the examples directory before executing each
# script, so Path.cwd() is the reliable way to locate sibling files.
examples_dir = Path.cwd()
sys.path.insert(0, str(examples_dir))

import mix1  # noqa: E402

# %%
# Serialize the running Cantera simulation to STONE YAML
# -------------------------------------------------------

output_yaml = "mixed_reactor_stream.yaml"
write_sim_as_yaml(mix1.sim, output_yaml)
print(f"Wrote STONE YAML to {output_yaml}")

# The STONE YAML can now be loaded in the Boulder GUI or re-solved below.
# From the command line:  sim2stone mix1.py

# %%
# Reload and re-solve from STONE YAML using BoulderRunner
# --------------------------------------------------------

runner = BoulderRunner.from_yaml(output_yaml)
runner.build()
assert runner.converter is not None
converter = runner.converter

print(
    f"Rebuilt network with {len(converter.reactors)} nodes and "
    f"{len(converter.connections)} connections."
)

# %%
# Verify the regenerated network matches the original
# ---------------------------------------------------

expected_nodes = {
    mix1.res_a.name,
    mix1.res_b.name,
    mix1.mixer.name,
    mix1.downstream.name,
}
assert set(converter.reactors.keys()) == expected_nodes
assert len(converter.connections) == 3
print("Network regeneration successful - all assertions passed!")
