# Extended reactor configuration
metadata:
  name: "Extended Reactor Configuration"
  description: "Multi-reservoir reactor system"
  version: "2.0"

simulation:
  mechanism: "gri30.yaml"
  time_step: 0.001
  max_time: 10.0
  solver_type: "CVODE_BDF"

components:
  - id: reactor1
    type: IdealGasReactor
    temperature: 1000
    pressure: 101325
    composition: "CH4:1,O2:2,N2:7.52"
    
  - id: res1
    type: Reservoir
    temperature: 800
    composition: "O2:1,N2:3.76"
    
  - id: downstream
    type: Reservoir
    temperature: 300
    pressure: 201325
    composition: "O2:1,N2:3.76"

connections:
  - id: mfc1
    type: MassFlowController
    source: res1
    target: reactor1
    mass_flow_rate: 0.1
    
  - id: mfc2
    type: MassFlowController
    source: reactor1
    target: downstream
    flow_rate: 0.1
