metadata:
  title: Mixing two streams
  description: Mixing of two inert streams in a stirred reactor.

phases:
  gas:
    mechanism: gri30.yaml

network:
- id: stream_a
  Reservoir:
    temperature: 300 K
    composition: N2:0.79,AR:0.21

- id: stream_b
  Reservoir:
    temperature: 300 K
    composition: N2:1

- id: mixer
  IdealGasReactor:
    volume: 0.001 m**3
    initial:
      temperature: 300 K
      pressure: 101325 Pa
      composition: N2:1

- id: outlet
  OutletSink:

- id: a_to_mixer
  MassFlowController:
    mass_flow_rate: 0.025 kg/s
  source: stream_a
  target: mixer

- id: b_to_mixer
  MassFlowController:
    mass_flow_rate: 0.015 kg/s
  source: stream_b
  target: mixer

- id: mixer_to_outlet
  Valve:
    valve_coeff: 10.0
  source: mixer
  target: outlet

settings: {}
