metadata:
  name: "Extended Reactor Configuration"
  description: "Multi-component reactor system with different flow controllers"
  version: "2.0"
  author: "Boulder Configuration System"

phases:
  gas:
    mechanism: gri30.yaml
settings:
  time_step: 0.001     # s
  max_time: 5.0        # s
  relative_tolerance: 1.0e-06
  absolute_tolerance: 1.0e-09
  max_steps: 10000

nodes:
- id: reactor1
  IdealGasReactor:
    temperature: 1200      # K
    pressure: 101325       # Pa
    composition: "CH4:1,O2:2,N2:7.52"
    volume: 0.01           # m³
- id: res1
  Reservoir:
    temperature: 300       # K
    composition: "O2:1,N2:3.76"
- id: res2
  Reservoir:
    temperature: 350       # K
    pressure: 202650       # Pa
    composition: "CH4:1"

connections:
- id: mfc1
  MassFlowController:
    mass_flow_rate: 0.05    # kg/s
  source: res1
  target: reactor1
- id: mfc2
  MassFlowController:
    mass_flow_rate: 0.02    # kg/s
  source: res2
  target: reactor1
